#!/usr/bin/env bash
set -o pipefail
[[ $DOKKU_TRACE ]] && set -x

fail() {
    echo "$@" 1>&2
    exit 1
}

check_container() {
  if [[ -z "$ID" ]]; then
    fail "Gnatsd container not started, cannot continue. Start with dokku gnatsd:create"
  fi
}

# Check if name is specified
if [[ $1 == gnatsd:* ]]; then
    if [ -z $2 ]; then
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi

    PLUGIN_NAME="gnatsd"
    CONTAINER_NAME="dokku-gnatsd"
    HOST_DIR="$DOKKU_ROOT/.$PLUGIN_NAME/storage"
    CONTAINER_IMAGE="apcera/gnatsd"
    GNATSD_PORT=4222
    MONITOR_PORT=8333
    if [[ ! -f $DOKKU_ROOT/.$PLUGIN_NAME/admin_pw ]]; then
        fail "Gnatsd password not set in $DOKKU_ROOT/.$PLUGIN_NAME/admin_pw. Did you run 'dokku plugins-install'?"
    fi
    GNATSD_PASS=$(cat "$DOKKU_ROOT/.$PLUGIN_NAME/admin_pw")

    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')

    if [[ -n "$ID" ]]; then
        GNATSD_PRIVATE_IP=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' ${ID})
    fi

fi


case "$1" in

  gnatsd:create)
    # Check if Gnatsd image is installed
    IMAGE=$(docker images | grep "$CONTAINER_IMAGE" |  awk '{print $3}')
    if [[ -z $IMAGE ]]; then
        fail "gnatsd image not found... Did you run 'dokku plugins-install' ?"
    fi
    # check for existing container with the same persistent gnatsd
    if [[ ! -z "$ID" ]]; then
        echo "" 1>&2
        fail "-----> Container $CONTAINER_NAME already exist. Please use rebuild or delete command"
    fi
    if [[ ! -d "$HOST_DIR" ]]; then
        mkdir -p "$HOST_DIR"
    fi
    # Check if an existing storage volume exists
    if [[ -d "$HOST_DIR/storage" ]]; then
        echo 
        echo "-----> Reusing $PLUGIN_NAME storage"
    else
        mkdir -p "$HOST_DIR/storage"
    fi
    # Check if gnatsd port already allocated
    if [[ -f "$HOST_DIR/PORT_GNATSD" ]]; then
        echo "-----> Reusing $PLUGIN_NAME gnatsd port"
        PORT_GNATSD=$(cat "$HOST_DIR/PORT_GNATSD")
    else
        PORT_GNATSD=""
    fi
    # Check if monitor port already allocated
    if [[ -f "$HOST_DIR/PORT_MONITOR" ]]; then
        echo "-----> Reusing $PLUGIN_NAME monitor port"
        PORT_MONITOR=$(cat "$HOST_DIR/PORT_MONITOR")
    else
        PORT_MONITOR=""
    fi
    # Launch container
    ID=$(docker run -p 127.0.0.1:$PORT_GNATSD:$GNATSD_PORT -p 127.0.0.1:$PORT_MONITOR:$MONITOR_PORT --name $CONTAINER_NAME -d $CONTAINER_IMAGE --user user --pass $GNATSD_PASS )
    sleep 1
    # store exposed ports
    PORT_GNATSD=$(docker port $ID $GNATSD_PORT | sed 's/127.0.0.1://')
    PORT_MONITOR=$(docker port $ID $MONITOR_PORT | sed 's/127.0.0.1://')
    echo $PORT_GNATSD > "$HOST_DIR/PORT_GNATSD"
    echo $PORT_MONITOR > "$HOST_DIR/PORT_MONITOR"

    echo
    echo "-----> Gnatsd container $CONTAINER_NAME created (using $CONTAINER_IMAGE)"
    sleep 1
    dokku gnatsd:info $CONTAINER_NAME
    ;;
  
  gnatsd:rebuild)
    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
    if [[ ! -z "$ID" ]]; then
        echo
        echo "-----> Stopping & removing $CONTAINER_NAME container"
        docker stop $ID > /dev/null
        docker rm $ID > /dev/null
    fi
    #TODO: create gnatsd without an app
    dokku gnatsd:create
    ;;

  gnatsd:delete)
    echo
    echo "-----> This will permanently remove all the stored data. Are you sure (yes/no)?"
    read ANSWER
    if [[ $ANSWER == "yes" ]]; then
        # Stop the container
        ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
        if [[ ! -z $ID ]]; then
            docker stop $ID > /dev/null
            docker rm $ID > /dev/null
        fi

        dokku gnatsd:unlink "$APP"

        # Remove persistent volume
        if [[ -d "$HOST_DIR" ]]; then
            rm -rf "$HOST_DIR"
            echo
            echo "-----> Deleted persistent storage for $CONTAINER_NAME"
        fi
        echo
        echo "-----> Deleted Gnatsd container $CONTAINER_NAME"
    fi
    ;;

  gnatsd:info)
    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
    IP=$(docker inspect $ID | grep IPAddress | awk '{ print $2 }' | tr -d ',"')
    DOCKER_GATEWAY=$(docker inspect $ID | grep Gateway | awk '{ print $2 }' | tr -d ',"')
    PORT_GNATSD=$(docker port $ID $GNATSD_PORT)
    PORT_MONITOR=$(docker port $ID $MONITOR_PORT)
    echo
    echo "       Host: $IP"
    echo "       Gateway: $DOCKER_GATEWAY"
    echo "       Gnatsd port: $GNATSD_PORT -> $PORT_GNATSD"
    echo "       Monitor port: $MONITOR_PORT -> $PORT_MONITOR"
    echo
    ;;

  gnatsd:link)
    APP="$2"
    if $APP_EXISTS; then
        dokku config:set --no-restart "$APP" \
            GNATSD_HOST="$GNATSD_PRIVATE_IP" \
            GNATSD_PORT="$GNATSD_PORT" \
            GNATSD_USERNAME="user" \
            GNATSD_PASSWORD="$GNATSD_PASS" \
            GNATSD_URL="nats://user:${GNATSD_PASS}@${GNATSD_PRIVATE_IP}:${GNATSD_PORT}" 

        echo
        echo "-----> $APP linked to gnatsd container"
    fi
    ;;

  gnatsd:unlink)
      APP="$2"
      if $APP_EXISTS; then
          dokku config:unset "$APP" \
              GNATSD_HOST \
              GNATSD_PORT \
              GNATSD_USERNAME \
              GNATSD_PASSWORD \
              GNATSD_URL
      fi
      ;;

  gnatsd:logs)
    ID=$(docker ps -a | grep "$CONTAINER_NAME" |  awk '{print $1}')
    docker logs $ID | tail -n 100
    ;;


  help)
    cat && cat<<EOF
    gnatsd:create                                  Starts the Gnatsd container
    gnatsd:rebuild                                Rebuild Gnatsd container (keep persistend data)
    gnatsd:delete                                 Delete Gnatsd container
    gnatsd:info                                   Display Gnatsd container informations
    gnatsd:link <app>                             Link an <app> to the Gnatsd container
    gnatsd:unlink <app>                           Unlink an <app> from the Gnatsd container
    gnatsd:logs                                   Display last logs from Gnatsd container
EOF
    ;;

  *)
    ;;
esac
